[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="07vkv9dv"
  NEXT_PUBLIC_SANITY_DATASET="production"
  NEXT_PUBLIC_SUPABASE_URL="https://kwdqpdliwypgsswdvdua.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZHFwZGxpd3lwZ3Nzd2R2ZHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NTkxMjAsImV4cCI6MjA4MzEzNTEyMH0.LwQocJQGuKd5HlhbrHklx_JeTf2jc415bxvcdQyg1uA"
  NEXT_PUBLIC_RESEND_API_KEY="re_LWsh9DY2_YqbwiFD6j2xA857QfCaPeqcu"
  NEXT_PUBLIC_PAYPAL_CLIENT_ID="AZu4e5C626GZK9yQLFY7Lyd8l4knFPlY4tf-ga38RYIi1T1rda970cHHCp9uzDN0rvTlVyjnVKW-BOzM"
  KLAVIYO_PRIVATE_API_KEY="pk_4f3370a7e0c82452b49c280779303a4c5a"

# Redirects for client-side environment
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Development context
[context.development]
  command = "npm run dev"

[context.development.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="07vkv9dv"
  NEXT_PUBLIC_SANITY_DATASET="production"
  NEXT_PUBLIC_SUPABASE_URL="https://kwdqpdliwypgsswdvdua.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZHFwZGxpd3lwZ3Nzd2R2ZHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NTkxMjAsImV4cCI6MjA4MzEzNTEyMH0.LwQocJQGuKd5HlhbrHklx_JeTf2jc415bxvcdQyg1uA"
  NEXT_PUBLIC_RESEND_API_KEY="re_LWsh9DY2_YqbwiFD6j2xA857QfCaPeqcu"
  NEXT_PUBLIC_PAYPAL_CLIENT_ID="AZu4e5C626GZK9yQLFY7Lyd8l4knFPlY4tf-ga38RYIi1T1rda970cHHCp9uzDN0rvTlVyjnVKW-BOzM"
  KLAVIYO_PRIVATE_API_KEY="pk_4f3370a7e0c82452b49c280779303a4c5a"

# Production context
[context.production]
  command = "npm run build"

[context.production.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="07vkv9dv"
  NEXT_PUBLIC_SANITY_DATASET="production"
  NEXT_PUBLIC_SUPABASE_URL="https://kwdqpdliwypgsswdvdua.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZHFwZGxpd3lwZ3Nzd2R2ZHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NTkxMjAsImV4cCI6MjA4MzEzNTEyMH0.LwQocJQGuKd5HlhbrHklx_JeTf2jc415bxvcdQyg1uA"
  NEXT_PUBLIC_RESEND_API_KEY="re_LWsh9DY2_YqbwiFD6j2xA857QfCaPeqcu"
  NEXT_PUBLIC_PAYPAL_CLIENT_ID="AZu4e5C626GZK9yQLFY7Lyd8l4knFPlY4tf-ga38RYIi1T1rda970cHHCp9uzDN0rvTlVyjnVKW-BOzM"
  KLAVIYO_PRIVATE_API_KEY="pk_4f3370a7e0c82452b49c280779303a4c5a"